### 회원가입 - MANAGER, CUSTOMER
POST http://localhost:8080/signup
Content-Type: application/json

{
  "username": "Customer2",
  "password": "1234",
  "email" : "asd@naver.com",
  "phone" : "01012345676",
  "userRole": "CUSTOMER"
}

### 로그인 - MANAGER, CUSTOMER
GET http://localhost:8080/signin
Content-Type: application/json

{
"username": "Customer2",
"password": "1234"
}

