spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ecommerce?serverTimezone=Asia/Seoul
    username:
    password: root
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true


