spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username:
    password: root
    url: jdbc:mariadb://localhost:3306/ecommerce?serverTimezone=Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true